feat: add collaboration type facet
molgenis/molgenis-app-biobank-explorer pull request #210
Opened 2020-12-18 13:29 UTC by jelmerveen

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] No warnings during install

2020-12-22 14:01 UTC, MaxPostema approved these changes

2020-12-22 14:17 UTC, MaxPostema commented on src/store/mutations.js
> +    state.nonCommercialCollections = collections.filter(c => !c.commercialUse).map(c => c.id)
Maybe give "c" a better name

2020-12-22 14:20 UTC, MaxPostema requested changes
In filter "Commercial use" is only selected with items in cart found with filter "Non-commercial use" selected. The selected items losse their "Non-commercial use" status?

I do not think that is correct.

2020-12-23 21:34 UTC, jelmerveen commented
> 
> 
> In filter "Commercial use" is only selected with items in cart found with filter "Non-commercial use" selected. The selected items losse their "Non-commercial use" status?
> 
> I do not think that is correct.

They are switched around indeed

2021-01-04 11:31 UTC, MaxPostema approved these changes

2021-01-04 11:33 UTC, merged