Adds combined_network attribute to collection entity
molgenis/molgenis-app-biobank-explorer pull request #299
Opened 2022-02-22 11:07 UTC by svituz

This PR adds the attribute called combined_network to the 'collection` entity.
The new attribute contains the combination of the networks of the collection and its biobank. It is necessary to contain all the networks the collection belongs to, either directly or indirectly (i.e., its biobank belongs to the network). Notice that the attribute 
will be filled by the transformer script that gets the network from the staging area of the National Nodes data.

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] No warnings during install
- [ ] Added to release notes

2022-02-23 10:20 UTC, svituz commented
Hi, I updated the new version of the model

2022-02-24 10:19 UTC, dtroelofsprins approved these changes

2022-02-24 10:23 UTC, dtroelofsprins requested changes
I've tested the model change in combination with adjustments in molgenis-py-bbmri-eric and it works fine. One small last remark. We agreed that this new combined_network field should become a hidden field. Could you please turn visible into false?

2022-03-01 11:05 UTC, dtroelofsprins approved these changes

2022-03-01 11:06 UTC, merged